### PR TITLE
Improve Makefile(s)

### PR DESCRIPTION
**Pull request by judearich**
This is a general refactoring of the Makefiles consisting of several improvements:

* Any architecture-independent rules or variables have been moved to the main Makefile to avoid duplication.
* Architecture sub-directories have been moved to the arch/ directory for better organization.
* Use `$(RM)` in `make clean` to fix a bug where `make clean` errors out if there's nothing to clean.
* `make` builds an release build, whereas `make debug` builds a debugging build.
* The architecture to make is now a a variable (`ARCH`) instead of separate rules for each architecture. Use `make ARCH=amd64` or `make ARCH=x86` to build a specific one, with  `amd64` being the default.

### CODE REVIEW

**Comment by Biswa96** [comment]
Also I was thinking about detecting the OS/build environment with which the compiler can be identified (if cross compiler or Windows native compiler e.g. mingw-w64).

**Comment by judearich** [comment]
I've heard making Makefiles that work on Windows and *nix is a compilcated game. I would say something like CMake or Meson would be a better alternative for a cross-platform build system.

**Comment by Biswa96** [comment]
Another thing, how about using [Automatic vairables](https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html) in the main Makefile? It may help to consolidate the make rules in 2-3 lines instead of every object files.

**Comment by judearich** [comment]
Good call, I did it plus I fixed some typos from earlier and specified PHONY targets.

**Comment by maharmstone** [comment]
Thanks for this, but I've switched to using cmake, which works both on Linux and with MSVC.

**Pull request closed without merging**
